/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-bg)',
        canvas: 'var(--color-bg)',
        surface: {
          DEFAULT: 'var(--color-surface)',
          card: 'var(--color-surface)',
          hover: 'var(--color-surface-hover)',
          subtle: 'var(--color-surface-subtle)',
          border: 'var(--color-border)',
          'border-strong': 'var(--color-border-strong)',
          muted: 'var(--color-text-muted)',
        },
        primary: {
          DEFAULT: 'var(--color-primary)',
          hover: 'var(--color-primary-hover)',
          active: 'var(--color-primary-active)',
          subtle: 'var(--color-primary-subtle)',
          border: 'var(--color-primary-border)',
          text: 'var(--color-primary-text)',
          50: 'var(--color-primary-subtle)',
          100: 'var(--color-primary-subtle)',
          200: 'var(--color-primary-border)',
          300: 'var(--color-primary-border)',
          400: 'var(--color-primary)',
          500: 'var(--color-primary)',
          600: 'var(--color-primary-hover)',
          700: 'var(--color-primary-active)',
          light: 'var(--color-primary-subtle)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          hover: 'var(--color-secondary-hover)',
          active: 'var(--color-secondary-active)',
          subtle: 'var(--color-secondary-subtle)',
          border: 'var(--color-secondary-border)',
          text: 'var(--color-secondary-text)',
          light: 'var(--color-secondary-subtle)',
        },
        tertiary: {
          DEFAULT: 'var(--color-tertiary)',
          hover: 'var(--color-tertiary-hover)',
          active: 'var(--color-tertiary-active)',
          subtle: 'var(--color-tertiary-subtle)',
          border: 'var(--color-tertiary-border)',
          text: 'var(--color-tertiary-text)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
          hover: 'var(--color-success-hover)',
          subtle: 'var(--color-success-subtle)',
          border: 'var(--color-success-border)',
          text: 'var(--color-success-text)',
          light: 'var(--color-success-subtle)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          hover: 'var(--color-warning-hover)',
          subtle: 'var(--color-warning-subtle)',
          border: 'var(--color-warning-border)',
          text: 'var(--color-warning-text)',
          light: 'var(--color-warning-subtle)',
        },
        danger: {
          DEFAULT: 'var(--color-danger)',
          hover: 'var(--color-danger-hover)',
          subtle: 'var(--color-danger-subtle)',
          border: 'var(--color-danger-border)',
          text: 'var(--color-danger-text)',
          light: 'var(--color-danger-subtle)',
        },
        info: {
          DEFAULT: 'var(--color-info)',
          hover: 'var(--color-info-hover)',
          subtle: 'var(--color-info-subtle)',
          border: 'var(--color-info-border)',
          text: 'var(--color-info-text)',
          light: 'var(--color-info-subtle)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
        },
        accent: {
          orange: 'var(--color-primary)',
          emerald: 'var(--color-success)',
          amber: 'var(--color-warning)',
          rose: 'var(--color-danger)',
          cyan: 'var(--color-tertiary)',
        },
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      boxShadow: {
        'soft': '0 2px 10px -2px rgba(15, 23, 42, 0.05), 0 1px 3px -1px rgba(15, 23, 42, 0.03)',
        'card': '0 4px 20px -2px rgba(15, 23, 42, 0.06), 0 2px 6px -1px rgba(15, 23, 42, 0.02)',
        'primary': '0 8px 20px -4px rgba(234, 88, 12, 0.22)',
      },
    },
  },
  plugins: [],
};
