import fs from 'node:fs';
import path from 'node:path';
import { TopicSchema, type Topic } from '../packages/shared/dist/index.mjs';

export const UNAUTHORED_TOPICS: Array<Omit<Topic, 'steps'> & { steps?: Record<string, any> }> = [
  {
    id: 'auth-oauth-sso',
    title: 'OAuth 2.0 & OIDC SSO Integration',
    category: 'authentication and authorization',
    difficulty: 'intermediate',
    prerequisites: ['auth-email-password'],
    learningObjectives: [
      'Understand Authorization Code Grant with PKCE',
      'Design account linking between local and social providers',
      'Handle token expiration, refresh tokens, and revocation',
    ],
    keyTradeoffs: [
      'PKCE vs Client Secret for single-page applications',
      'Immediate user creation vs explicit email matching confirmation',
    ],
    commonPitfalls: [
      'Failing to validate the state parameter (CSRF vulnerability)',
      'Storing provider access tokens in local storage',
      'Overwriting existing local credentials during social login',
    ],
    transferTopicId: 'auth-mfa-totp',
    transferPrompt: 'How would you add multi-factor authentication (MFA) on top of an existing OAuth flow?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 15,
    tags: ['auth', 'oauth', 'oidc', 'sso'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'auth-rbac-permissions',
    title: 'Role-Based Access Control & Permissions Engine',
    category: 'authentication and authorization',
    difficulty: 'intermediate',
    prerequisites: ['auth-email-password', 'db-relational-schema'],
    learningObjectives: [
      'Model Users, Roles, Permissions, and Resource Scopes',
      'Design caching and evaluation strategies for sub-millisecond authorization checks',
      'Handle hierarchical roles and tenant isolation in multi-tenant SaaS',
    ],
    keyTradeoffs: [
      'RBAC vs ABAC (Attribute-Based Access Control)',
      'Evaluating permissions in database queries vs application memory',
    ],
    commonPitfalls: [
      'Hardcoding permission checks by role name instead of granular permission slug',
      'N+1 query cascades when checking row-level permissions on lists',
    ],
    transferTopicId: 'auth-oauth-sso',
    transferPrompt: 'How would you synchronize user roles and claims from an external IdP (like Okta) into your RBAC schema?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['auth', 'rbac', 'permissions', 'security'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'auth-password-reset',
    title: 'Secure Password Reset & Magic Links',
    category: 'authentication and authorization',
    difficulty: 'beginner',
    prerequisites: ['auth-email-password'],
    learningObjectives: [
      'Design cryptographically secure, single-use, time-limited reset tokens',
      'Mitigate account enumeration attacks in reset request forms',
      'Invalidate existing active sessions upon successful password changes',
    ],
    keyTradeoffs: [
      'Stateless signed tokens (HMAC) vs stored hash in database',
      'Immediate login after reset vs requiring re-authentication',
    ],
    commonPitfalls: [
      'Returning distinct HTTP status codes or timing variations for registered vs unregistered emails',
      'Allowing reset tokens to be reused multiple times within the expiry window',
    ],
    transferTopicId: 'auth-mfa-totp',
    transferPrompt: 'If a compromised email account requests password resets, what additional verification factors would protect the user?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 15,
    tags: ['auth', 'password-reset', 'security'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'auth-mfa-totp',
    title: 'Multi-Factor Authentication via TOTP',
    category: 'authentication and authorization',
    difficulty: 'intermediate',
    prerequisites: ['auth-email-password'],
    learningObjectives: [
      'Understand RFC 6238 Time-based One-Time Password algorithm',
      'Securely encrypt TOTP shared secrets at rest',
      'Design emergency single-use backup recovery codes',
    ],
    keyTradeoffs: [
      'App-based TOTP vs SMS/Email verification codes',
      'Grace periods for clock drift (30-second steps vs 60-second window)',
    ],
    commonPitfalls: [
      'Storing TOTP secrets in plaintext in the user table',
      'Accepting the same 6-digit TOTP code multiple times within the time step window',
    ],
    transferTopicId: 'auth-session-jwt',
    transferPrompt: 'How does session state and token issuance change between step 1 (passphrase) and step 2 (TOTP verification)?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['auth', 'mfa', 'totp', 'security'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'auth-session-jwt',
    title: 'Session Management vs Stateless JWTs',
    category: 'authentication and authorization',
    difficulty: 'intermediate',
    prerequisites: ['auth-email-password'],
    learningObjectives: [
      'Compare server-side session stores with stateless JSON Web Tokens',
      'Design revocation strategies for distributed tokens (blacklists, token versioning)',
      'Secure HttpOnly cookie storage vs Authorization bearer tokens',
    ],
    keyTradeoffs: [
      'Instant revocation capability vs zero-database-lookup verification performance',
      'Payload size and network overhead on high-throughput microservices',
    ],
    commonPitfalls: [
      'Storing sensitive credentials or excessive claims inside JWT payload',
      'Accepting the `none` algorithm or weak signing secrets',
    ],
    transferTopicId: 'cache-redis-patterns',
    transferPrompt: 'How would you leverage Redis to implement hybrid short-lived JWTs with central session revocation?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 15,
    tags: ['auth', 'sessions', 'jwt', 'security'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'db-migrations-zero-downtime',
    title: 'Zero-Downtime Database Schema Migrations',
    category: 'data and storage',
    difficulty: 'advanced',
    prerequisites: ['db-relational-schema'],
    learningObjectives: [
      'Apply Expand and Contract (Parallel Run) migration pattern',
      'Safely rename and split database columns in active production systems',
      'Add NOT NULL constraints and foreign keys without locking large tables',
    ],
    keyTradeoffs: [
      'Dual-writing in application code vs database triggers during transition phases',
      'Immediate column deletion vs gradual deprecation lifecycle',
    ],
    commonPitfalls: [
      'Running ALTER TABLE ADD COLUMN with volatile defaults on millions of rows',
      'Deploying new application code before verifying backwards-compatible database schema',
    ],
    transferTopicId: 'db-sharding-partitioning',
    transferPrompt: 'How do schema migrations differ when tables are horizontally sharded across multiple database clusters?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 25,
    tags: ['database', 'migrations', 'devops', 'zero-downtime'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'db-sharding-partitioning',
    title: 'Horizontal Database Sharding & Partitioning',
    category: 'data and storage',
    difficulty: 'advanced',
    prerequisites: ['db-relational-schema'],
    learningObjectives: [
      'Select partition keys to balance write loads and avoid hot spots',
      'Compare range-based, hash-based, and directory-based sharding architectures',
      'Handle cross-shard queries and distributed transactions',
    ],
    keyTradeoffs: [
      'Application-level sharding vs transparent distributed database engines (Citrus, Vitess)',
      'Co-locating related entity tables vs uniform horizontal data distribution',
    ],
    commonPitfalls: [
      'Choosing a monotonically increasing ID as partition key (causing single-shard write bottleneck)',
      'Executing unindexed scatter-gather queries across all database shards',
    ],
    transferTopicId: 'db-read-replicas',
    transferPrompt: 'When should a team choose read replicas over sharding for scaling database read bottlenecks?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 25,
    tags: ['database', 'sharding', 'scalability', 'partitioning'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'db-read-replicas',
    title: 'Read Replicas & Eventual Consistency',
    category: 'data and storage',
    difficulty: 'intermediate',
    prerequisites: ['db-relational-schema'],
    learningObjectives: [
      'Route read-only queries to secondary replicas while directing writes to primary',
      'Mitigate replication lag and read-your-own-writes inconsistencies',
      'Implement sticky sessions or session-consistency tokens for user actions',
    ],
    keyTradeoffs: [
      'Synchronous vs asynchronous replication overhead and durability guarantees',
      'Query router middleware vs separate connection pools in application code',
    ],
    commonPitfalls: [
      'Showing stale data to a user immediately after they submit a profile or checkout update',
      'Overwhelming primary when replica lag monitor trips fallback switches',
    ],
    transferTopicId: 'cache-redis-patterns',
    transferPrompt: 'How does caching with Redis interact with replica lag in a high-traffic read environment?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['database', 'replication', 'consistency', 'scalability'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'db-nosql-document',
    title: 'NoSQL Document Store Modeling',
    category: 'data and storage',
    difficulty: 'intermediate',
    prerequisites: ['db-relational-schema'],
    learningObjectives: [
      'Model entities with embedded documents vs normalized references',
      'Design query-first schema patterns optimized for single-read retrieval',
      'Enforce atomic updates using optimistic concurrency control (CAS / version fields)',
    ],
    keyTradeoffs: [
      'Denormalization write amplification vs low-latency document read speeds',
      'Document size limits (e.g. MongoDB 16MB) vs splitting into subcollections',
    ],
    commonPitfalls: [
      'Treating a document store like an RDBMS and attempting client-side multi-table joins',
      'Unbounded array growth inside a single document',
    ],
    transferTopicId: 'search-elasticsearch',
    transferPrompt: 'When query patterns require arbitrary multi-field filtering, how do you pair document stores with full-text search indexes?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['database', 'nosql', 'mongodb', 'schema'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'db-timeseries-metrics',
    title: 'Time-Series Metrics & Analytics Storage',
    category: 'data and storage',
    difficulty: 'advanced',
    prerequisites: ['db-relational-schema'],
    learningObjectives: [
      'Design rollups, downsampling, and automated data retention policies',
      'Structure high-cardinality tag and measurement indexes',
      'Evaluate storage engines: ClickHouse, TimescaleDB, and specialized TSDBs',
    ],
    keyTradeoffs: [
      'Columnar compression efficiency vs row-based point-lookup performance',
      'Pre-aggregated summary tables vs real-time streaming calculation pipelines',
    ],
    commonPitfalls: [
      'Uncontrolled high cardinality dimensions (e.g. raw UUIDs as index tags)',
      'Writing individual single-row inserts rather than micro-batched write streams',
    ],
    transferTopicId: 'obs-distributed-tracing',
    transferPrompt: 'How does time-series metric storage differ in query patterns and indexing from distributed trace storage?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 25,
    tags: ['database', 'timeseries', 'analytics', 'clickhouse'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'api-graphql-design',
    title: 'GraphQL API Design & Schema Federation',
    category: 'APIs',
    difficulty: 'advanced',
    prerequisites: ['api-restful-design'],
    learningObjectives: [
      'Solve the N+1 problem with DataLoader batching and caching',
      'Design schema federation across autonomous microservice teams',
      'Enforce query complexity and depth limits to prevent denial-of-service',
    ],
    keyTradeoffs: [
      'Client flexibility in field selection vs backend query optimization and CDN caching',
      'Code-first vs schema-first development workflows',
    ],
    commonPitfalls: [
      'Exposing unbounded recursive relations that allow malicious nested queries',
      'Missing rate limiting because all requests hit a single `/graphql` POST endpoint',
    ],
    transferTopicId: 'api-restful-design',
    transferPrompt: 'When is a simple REST or RPC endpoint preferable over expanding a federated GraphQL graph?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['api', 'graphql', 'federation', 'microservices'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'api-grpc-services',
    title: 'gRPC Microservice Communication & Protobufs',
    category: 'APIs',
    difficulty: 'intermediate',
    prerequisites: ['api-restful-design'],
    learningObjectives: [
      'Define binary message contracts using Protocol Buffers (proto3)',
      'Leverage HTTP/2 multiplexing, bidirectional streaming, and header compression',
      'Implement deadline propagation and context cancellation across microservices',
    ],
    keyTradeoffs: [
      'Binary serialization speed and type safety vs human-readable JSON debuggability',
      'Browser client compatibility via gRPC-Web vs standard REST gateways',
    ],
    commonPitfalls: [
      'Reusing or renumbering proto field tags, breaking backwards compatibility',
      'Neglecting to set and propagate client call timeouts across call chains',
    ],
    transferTopicId: 'obs-distributed-tracing',
    transferPrompt: 'How do you propagate W3C Trace Context and correlation IDs across gRPC metadata boundaries?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['api', 'grpc', 'protobuf', 'microservices'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'api-webhooks-delivery',
    title: 'Outbound Webhook Delivery & At-Least-Once Guarantees',
    category: 'APIs',
    difficulty: 'intermediate',
    prerequisites: ['api-restful-design'],
    learningObjectives: [
      'Sign payloads with HMAC-SHA256 and timestamp headers to prevent replay attacks',
      'Implement exponential backoff retry schedules for failing customer endpoints',
      'Isolate tenant delivery queues so slow consumer endpoints do not block others',
    ],
    keyTradeoffs: [
      'Immediate delivery synchronous HTTP calls vs background worker queue dispatch',
      'Strict ordered delivery per resource vs high-throughput concurrent deliveries',
    ],
    commonPitfalls: [
      'Failing to verify recipient SSL certificates or following unbounded redirect chains (SSRF risks)',
      'Retrying without jitter, causing thundering herds on customer servers when they recover',
    ],
    transferTopicId: 'api-idempotency-keys',
    transferPrompt: 'How should webhook consumers use idempotency keys and event IDs to handle duplicate deliveries gracefully?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['api', 'webhooks', 'security', 'integration'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'api-idempotency-keys',
    title: 'Idempotent API Architecture & Deduplication',
    category: 'APIs',
    difficulty: 'intermediate',
    prerequisites: ['api-restful-design'],
    learningObjectives: [
      'Implement the Idempotency-Key header pattern for mutating POST requests',
      'Manage atomic reservation, processing locks, and cached response storage',
      'Handle concurrent identical requests with HTTP 409 Conflict or lock waits',
    ],
    keyTradeoffs: [
      'Database transactional locking vs Redis distributed locks for in-flight requests',
      'Storing full response body payloads vs returning idempotent status pointers',
    ],
    commonPitfalls: [
      'Caching idempotent responses before verifying that the underlying transaction succeeded',
      'Failing to scope idempotency keys to individual authenticated users/tenants',
    ],
    transferTopicId: 'pay-stripe-checkout',
    transferPrompt: 'How does payment processing rely on idempotency keys to prevent accidental double-charging during network blips?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['api', 'idempotency', 'reliability', 'transactions'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'jobs-async-queues',
    title: 'Asynchronous Background Job Processing & Dead-Letter Queues',
    category: 'async/background jobs',
    difficulty: 'intermediate',
    prerequisites: ['api-restful-design'],
    learningObjectives: [
      'Decouple heavy processing from HTTP request cycles using reliable message brokers',
      'Design idempotent job workers that survive ungraceful process crashes',
      'Configure Dead-Letter Queues (DLQ) and alerting for unrecoverable poisonous messages',
    ],
    keyTradeoffs: [
      'Redis-based lightweight queues (BullMQ) vs distributed persistent logs (RabbitMQ, SQS, Kafka)',
      'At-least-once processing guarantees vs at-most-once performance',
    ],
    commonPitfalls: [
      'Passing large payload objects in job metadata instead of entity IDs',
      'Lacking dead-letter queue limits, allowing malformed poison pill jobs to loop endlessly',
    ],
    transferTopicId: 'jobs-distributed-cron',
    transferPrompt: 'How do you coordinate recurring scheduled batch jobs using queue workers without duplicate task execution?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['jobs', 'queues', 'async', 'workers'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'jobs-distributed-cron',
    title: 'Distributed Scheduled Tasks & Cron Coordination',
    category: 'async/background jobs',
    difficulty: 'intermediate',
    prerequisites: ['jobs-async-queues'],
    learningObjectives: [
      'Prevent duplicate execution of scheduled jobs in horizontally scaled clusters',
      'Implement distributed leader election or distributed mutex locks (Redlock)',
      'Handle job drift, missed schedules during outages, and catch-up policies',
    ],
    keyTradeoffs: [
      'Centralized cloud scheduler (e.g. AWS EventBridge) vs application-level distributed scheduler',
      'Catch-up execution of historical intervals vs skipping to current clock time',
    ],
    commonPitfalls: [
      'Assuming a single server will run standard Unix cron when deployed in Kubernetes pods',
      'Lock expiration that occurs while a long-running batch job is still executing',
    ],
    transferTopicId: 'jobs-event-driven-pubsub',
    transferPrompt: 'How can recurring jobs emit events to a pub/sub bus to decouple triggers from execution logic?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 15,
    tags: ['cron', 'jobs', 'distributed-systems', 'scheduling'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'jobs-event-driven-pubsub',
    title: 'Event-Driven Pub/Sub & Stream Processing',
    category: 'async/background jobs',
    difficulty: 'advanced',
    prerequisites: ['jobs-async-queues'],
    learningObjectives: [
      'Design event schemas with backward and forward compatibility',
      'Differentiate point-to-point queues from broadcast publish/subscribe models',
      'Manage consumer groups, partition offsets, and message ordering semantics',
    ],
    keyTradeoffs: [
      'Partition-key ordering guarantees vs total throughput parallelism',
      'Event sourcing full state derivation vs lightweight change data capture (CDC)',
    ],
    commonPitfalls: [
      'Publishing events before the database transaction has successfully committed (dual-write hazard)',
      'Consumers failing to handle out-of-order event delivery',
    ],
    transferTopicId: 'realtime-websockets-chat',
    transferPrompt: 'How does a pub/sub cluster fan out messages across distributed WebSocket gateway nodes?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 25,
    tags: ['events', 'pubsub', 'kafka', 'architecture'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'notif-multi-channel',
    title: 'Multi-Channel Notification Fanout (Email, SMS, Push)',
    category: 'notifications',
    difficulty: 'intermediate',
    prerequisites: ['jobs-async-queues'],
    learningObjectives: [
      'Design unified notification schemas with provider-specific adapter templates',
      'Implement fallback routing across external gateways (e.g. Twilio, SendGrid, FCM)',
      'Track delivery states (sent, delivered, opened, bounced) through webhooks',
    ],
    keyTradeoffs: [
      'Immediate delivery cascade vs batching notification digests',
      'In-house template rendering vs third-party notification platforms',
    ],
    commonPitfalls: [
      'Blocking user-facing requests on external SMTP/SMS network calls',
      'Failing to handle hard bounces and spam complaints, leading to IP reputation burn',
    ],
    transferTopicId: 'notif-user-preferences',
    transferPrompt: 'How does notification fanout check customer preference rules and quiet hours before sending messages?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['notifications', 'email', 'sms', 'push'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'notif-user-preferences',
    title: 'Notification Preference Center & Frequency Caps',
    category: 'notifications',
    difficulty: 'beginner',
    prerequisites: ['db-relational-schema'],
    learningObjectives: [
      'Model granular category, channel, and frequency preference rules',
      'Implement rate-limiting and deduplication frequency caps (anti-spam)',
      'Honor regulatory unsubscribe mandates (CAN-SPAM, GDPR) via one-click signed tokens',
    ],
    keyTradeoffs: [
      'Opt-in default vs opt-out default for non-transactional messages',
      'Evaluating preferences in worker queues vs filtering at the event producer',
    ],
    commonPitfalls: [
      'Sending marketing emails to users who explicitly unsubscribed, triggering legal penalties',
      'Flooding a user with 50 duplicate push notifications when a single batch event fires',
    ],
    transferTopicId: 'notif-multi-channel',
    transferPrompt: 'How would you test and verify preference compliance in automated integration tests?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 15,
    tags: ['notifications', 'preferences', 'gdpr', 'compliance'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'search-elasticsearch',
    title: 'Full-Text Search with Elasticsearch',
    category: 'search',
    difficulty: 'advanced',
    prerequisites: ['db-relational-schema'],
    learningObjectives: [
      'Configure tokenizers, stemmers, and analyzers for multi-language search',
      'Sync database state to search indexes using Transactional Outbox or CDC',
      'Structure multi-match queries with field boosting and fuzzy matching',
    ],
    keyTradeoffs: [
      'Real-time indexing lag vs primary database write latency',
      'Elasticsearch cluster operational overhead vs PostgreSQL pg_trgm / tsvector',
    ],
    commonPitfalls: [
      'Using Elasticsearch as the primary source of truth rather than a secondary index',
      'Mapping explosion caused by dynamic field generation from arbitrary user JSON',
    ],
    transferTopicId: 'search-autocomplete',
    transferPrompt: 'How does full-text document search differ in indexing structures from instant prefix autocomplete?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 25,
    tags: ['search', 'elasticsearch', 'indexing', 'fulltext'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'search-autocomplete',
    title: 'Typeahead & Autocomplete Search Engine',
    category: 'search',
    difficulty: 'intermediate',
    prerequisites: ['search-elasticsearch'],
    learningObjectives: [
      'Design prefix trees (Trie) and n-gram indexes for sub-50ms query latency',
      'Implement popularity and recency ranking algorithms',
      'Cache top search prefixes in Redis edge caches',
    ],
    keyTradeoffs: [
      'Edge CDN caching of common prefixes vs personalized query suggestions',
      'Pre-computed completion dictionaries vs dynamic inverted index querying',
    ],
    commonPitfalls: [
      'Triggering backend network requests on every keystroke without client-side debouncing',
      'Case-sensitivity and accent mismatching in prefix lookups',
    ],
    transferTopicId: 'cache-redis-patterns',
    transferPrompt: 'How can Redis Sorted Sets (ZSET) be used to store and rank autocomplete completions?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 15,
    tags: ['search', 'autocomplete', 'typeahead', 'trie'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'pay-stripe-checkout',
    title: 'Subscription Billing & Stripe Webhook Integration',
    category: 'payments',
    difficulty: 'intermediate',
    prerequisites: ['api-webhooks-delivery', 'db-relational-schema'],
    learningObjectives: [
      'Implement secure Stripe Checkout and Customer Portal redirects',
      'Process asynchronous subscription lifecycle events via webhooks',
      'Handle invoice payment failures, dunning emails, and grace periods',
    ],
    keyTradeoffs: [
      'Hosted checkout sessions vs custom in-app credit card elements (PCI compliance)',
      'Immediate access grant vs waiting for webhook confirmation',
    ],
    commonPitfalls: [
      'Trusting client-side payment completion redirects without verifying signed webhooks',
      'Failing to handle out-of-order webhook delivery (e.g. invoice created after subscription deleted)',
    ],
    transferTopicId: 'pay-ledger-double-entry',
    transferPrompt: 'How do you record external Stripe payment charges into an internal double-entry ledger?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['payments', 'stripe', 'billing', 'subscriptions'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'pay-ledger-double-entry',
    title: 'Double-Entry Accounting Ledger System',
    category: 'payments',
    difficulty: 'advanced',
    prerequisites: ['db-relational-schema'],
    learningObjectives: [
      'Model immutable Journal Entries with balanced Debits and Credits',
      'Enforce atomic balance constraints across multiple asset, liability, and equity accounts',
      'Design append-only ledger tables with cryptographic hash chaining (auditability)',
    ],
    keyTradeoffs: [
      'Real-time account balance calculation vs cached running balance tables',
      'Strict database serializable isolation vs optimistic concurrency locking',
    ],
    commonPitfalls: [
      'Using floating-point numbers instead of integer minor units (cents) or fixed-point decimals',
      'Allowing UPDATE or DELETE operations on ledger transaction rows',
    ],
    transferTopicId: 'pay-refund-reconciliation',
    transferPrompt: 'How do ledger entries record reversals and chargebacks while preserving immutable transaction history?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 25,
    tags: ['payments', 'ledger', 'accounting', 'fintech'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'pay-refund-reconciliation',
    title: 'Payment Reconciliation & Chargeback Handling',
    category: 'payments',
    difficulty: 'advanced',
    prerequisites: ['pay-ledger-double-entry'],
    learningObjectives: [
      'Reconcile internal transaction ledgers with external bank settlement files',
      'Model partial refunds, dispute workflows, and penalty fee allocation',
      'Generate automated variance reports and audit trails',
    ],
    keyTradeoffs: [
      'Automated automated settlement matching vs manual exceptions workflow',
      'Immediate merchant account debit on dispute notice vs holding reserves',
    ],
    commonPitfalls: [
      'Refunding more than the original captured charge amount',
      'Failing to account for currency exchange fluctuations between charge date and settlement date',
    ],
    transferTopicId: 'pay-stripe-checkout',
    transferPrompt: 'How do gateway chargeback webhooks trigger automatic license/subscription revocations in your app?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['payments', 'reconciliation', 'chargebacks', 'fintech'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'file-s3-direct-upload',
    title: 'Direct Pre-Signed S3 File Uploads & Antivirus Scanning',
    category: 'file handling',
    difficulty: 'intermediate',
    prerequisites: ['api-restful-design'],
    learningObjectives: [
      'Generate pre-signed S3/GCS PUT URLs with strict content-type and size limits',
      'Prevent server bottlenecking by bypassing API servers for large file uploads',
      'Trigger asynchronous malware/antivirus scanning before making uploaded files public',
    ],
    keyTradeoffs: [
      'Direct client-to-storage upload vs API proxy streaming',
      'Pre-signed POST with policy conditions vs pre-signed PUT URLs',
    ],
    commonPitfalls: [
      'Allowing public read access on bucket uploads before security inspection completes',
      'Trusting client-reported MIME types without inspecting magic bytes',
    ],
    transferTopicId: 'file-image-processing',
    transferPrompt: 'Once a raw image file lands in S3, how do you trigger automated thumbnail generation pipelines?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['files', 's3', 'storage', 'security'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'file-image-processing',
    title: 'On-Demand Image Processing & CDN Delivery',
    category: 'file handling',
    difficulty: 'intermediate',
    prerequisites: ['file-s3-direct-upload'],
    learningObjectives: [
      'Implement on-demand image resizing, cropping, and WebP/AVIF format conversion',
      'Cache transformed variants on global CDN edge nodes',
      'Protect dynamic transform endpoints with HMAC signature validation (anti-DDoS)',
    ],
    keyTradeoffs: [
      'Pre-generating all size variants at upload time vs on-demand edge generation',
      'Self-hosted Sharp/Libvips service vs cloud provider image services (Cloudinary)',
    ],
    commonPitfalls: [
      'Unsigned transform URLs allowing attackers to exhaust CPU and storage with arbitrary size permutations',
      'Missing cache-control headers on immutable processed image assets',
    ],
    transferTopicId: 'file-csv-streaming',
    transferPrompt: 'How does high-throughput binary image streaming differ from streaming large CSV text exports?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 15,
    tags: ['files', 'images', 'cdn', 'performance'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'file-csv-streaming',
    title: 'Large CSV File Export & Streaming Processing',
    category: 'file handling',
    difficulty: 'intermediate',
    prerequisites: ['db-relational-schema'],
    learningObjectives: [
      'Stream million-row database exports without buffering entire datasets into memory',
      'Manage HTTP chunked transfer encoding and browser backpressure',
      'Sanitize spreadsheet formulas to prevent CSV Injection (Formula Injection) attacks',
    ],
    keyTradeoffs: [
      'Real-time streaming HTTP downloads vs asynchronous background generation with download link',
      'Cursor-based pagination vs database streaming cursors',
    ],
    commonPitfalls: [
      'Loading entire million-row query results into Node.js heap memory, causing Out-Of-Memory crashes',
      'Allowing cells starting with `=`, `+`, `-`, or `@` without escaping, executing code in Excel',
    ],
    transferTopicId: 'jobs-async-queues',
    transferPrompt: 'When file exports exceed 500MB, how do you offload generation to background queue workers?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['files', 'csv', 'streaming', 'memory-management'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'realtime-websockets-chat',
    title: 'Scalable WebSockets Chat Architecture',
    category: 'real-time features',
    difficulty: 'advanced',
    prerequisites: ['auth-session-jwt'],
    learningObjectives: [
      'Establish authenticated persistent WebSocket connections',
      'Scale WebSocket connection servers across a horizontal cluster using Redis Pub/Sub',
      'Implement heartbeat pings, exponential reconnects, and message delivery receipts',
    ],
    keyTradeoffs: [
      'WebSockets vs Server-Sent Events (SSE) for bidirectional vs unidirectional streaming',
      'Ephemeral in-memory message passing vs persistent database chat transcripts',
    ],
    commonPitfalls: [
      'Storing user socket connections on a single server without cross-server pub/sub broadcast',
      'Failing to authenticate connection upgrades before accepting WebSocket handshakes',
    ],
    transferTopicId: 'realtime-presence-system',
    transferPrompt: 'How do you layer real-time online/offline presence tracking on top of active WebSocket connections?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 25,
    tags: ['realtime', 'websockets', 'chat', 'scalability'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'realtime-presence-system',
    title: 'User Online Presence & Heartbeat Tracking',
    category: 'real-time features',
    difficulty: 'intermediate',
    prerequisites: ['realtime-websockets-chat'],
    learningObjectives: [
      'Design heartbeat pings and TTL-based key expiry in Redis for presence detection',
      'Broadcast presence transitions (online, idle, offline) efficiently to followers',
      'Handle connection flapping and brief network drops without false offline alerts',
    ],
    keyTradeoffs: [
      'Continuous active heartbeats vs passive request-driven last-seen timestamps',
      'Immediate broadcast of every presence change vs batched delta updates',
    ],
    commonPitfalls: [
      'Flooding network sockets by broadcasting presence changes to millions of irrelevant users',
      'Setting heartbeat TTLs too short, triggering spurious offline flickers during momentary packet loss',
    ],
    transferTopicId: 'realtime-collaborative-editing',
    transferPrompt: 'How is user presence combined with cursor coordinates in collaborative document workspaces?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 15,
    tags: ['realtime', 'presence', 'redis', 'websockets'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'realtime-collaborative-editing',
    title: 'Operational Transformation & CRDT Collaboration',
    category: 'real-time features',
    difficulty: 'advanced',
    prerequisites: ['realtime-websockets-chat'],
    learningObjectives: [
      'Compare Conflict-free Replicated Data Types (CRDTs) with Operational Transformation (OT)',
      'Resolve concurrent conflicting edits without a single centralized locking authority',
      'Structure document state trees and local optimistic mutation playback',
    ],
    keyTradeoffs: [
      'CRDT metadata memory overhead vs OT central server coordination requirements',
      'Character-by-character synchronization vs block-level document updates',
    ],
    commonPitfalls: [
      'Assuming client clocks are synchronized when ordering concurrent edits',
      'Unbounded tombstone growth in memory for deleted document nodes in CRDT structures',
    ],
    transferTopicId: 'db-nosql-document',
    transferPrompt: 'How do you persist collaborative document states into a database while preserving undo/redo history?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 25,
    tags: ['realtime', 'crdt', 'collaboration', 'distributed-systems'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'cache-redis-patterns',
    title: 'Redis Caching Patterns: Cache-Aside vs Write-Through',
    category: 'caching',
    difficulty: 'intermediate',
    prerequisites: ['db-relational-schema'],
    learningObjectives: [
      'Implement Cache-Aside, Write-Through, and Write-Behind caching strategies',
      'Determine appropriate Time-To-Live (TTL) policies and eviction strategies (LRU, LFU)',
      'Design composite cache keys and namespace invalidation patterns',
    ],
    keyTradeoffs: [
      'Read-heavy cache-aside simplicity vs write-through data consistency guarantees',
      'Memory cost of high TTL caches vs database query load on cache misses',
    ],
    commonPitfalls: [
      'Setting identical TTLs on thousands of cached keys, causing synchronized mass expiration',
      'Caching null or error responses improperly without a short protective TTL',
    ],
    transferTopicId: 'cache-stampede-prevention',
    transferPrompt: 'What happens when a hot cache key expires while thousands of concurrent requests arrive simultaneously?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['caching', 'redis', 'performance', 'architecture'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'cache-stampede-prevention',
    title: 'Cache Invalidation, Thundering Herd & Dogpiling',
    category: 'caching',
    difficulty: 'advanced',
    prerequisites: ['cache-redis-patterns'],
    learningObjectives: [
      'Prevent Cache Stampedes (Dogpiling / Thundering Herd) using probabilistic early expiration (XFetch)',
      'Implement distributed single-flight query coalescing and mutex locking',
      'Design reliable cache invalidation patterns via event-driven pub/sub',
    ],
    keyTradeoffs: [
      'Serving stale data while background refresh completes vs blocking client threads on cache misses',
      'Probabilistic early recomputation CPU cost vs deterministic TTL simplicity',
    ],
    commonPitfalls: [
      'Allowing 10,000 concurrent web requests to hit PostgreSQL at once when a homepage cache key expires',
      'Deadlocks in distributed cache locking implementations',
    ],
    transferTopicId: 'rate-limiting-token-bucket',
    transferPrompt: 'How can rate limiters protect backends when cache layers fail or are completely flushed?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['caching', 'stampede', 'thundering-herd', 'resilience'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'rate-limiting-token-bucket',
    title: 'Distributed Token Bucket & Leaky Bucket Rate Limiting',
    category: 'rate limiting',
    difficulty: 'intermediate',
    prerequisites: ['api-restful-design'],
    learningObjectives: [
      'Understand Token Bucket, Leaky Bucket, and Sliding Window Counter algorithms',
      'Implement atomic distributed rate limiting using Redis Lua scripts',
      'Return standard IETF draft RateLimit headers (`RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset`)',
    ],
    keyTradeoffs: [
      'Fixed window memory efficiency vs sliding window boundary burst protection',
      'Local in-process rate limiting vs central distributed Redis evaluation',
    ],
    commonPitfalls: [
      'Non-atomic get-and-increment operations in Redis that cause race conditions under high concurrency',
      'Failing to include `Retry-After` headers on HTTP 429 Too Many Requests responses',
    ],
    transferTopicId: 'rate-limiting-tier-quotas',
    transferPrompt: 'How do you layer monthly subscription quota limits on top of second-by-second burst rate limiting?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['ratelimiting', 'redis', 'algorithms', 'security'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'rate-limiting-tier-quotas',
    title: 'Multi-Tier API Quotas & Tenant Throttling',
    category: 'rate limiting',
    difficulty: 'intermediate',
    prerequisites: ['rate-limiting-token-bucket'],
    learningObjectives: [
      'Design multi-tier quota limits (Free vs Pro vs Enterprise) per API key',
      'Implement fair-share tenant resource throttling to prevent noisy-neighbor degradation',
      'Track monthly rollover usage and send usage warning notifications',
    ],
    keyTradeoffs: [
      'Hard cut-off on quota exhaustion vs billing for overages with soft throttling',
      'Evaluating usage in API gateway middleware vs asynchronous billing aggregation',
    ],
    commonPitfalls: [
      'A single free-tier customer consuming 100% of available backend database connections',
      'Timezone mismatch bugs when resetting monthly quota allowances',
    ],
    transferTopicId: 'api-restful-design',
    transferPrompt: 'How do you design API responses and error codes when a customer exceeds their paid tier quota?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['ratelimiting', 'quotas', 'saas', 'multitenancy'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'obs-distributed-tracing',
    title: 'Distributed Tracing with OpenTelemetry',
    category: 'observability',
    difficulty: 'advanced',
    prerequisites: ['api-grpc-services'],
    learningObjectives: [
      'Propagate W3C Traceparent headers across HTTP, gRPC, and message queues',
      'Model Spans, Traces, Attributes, and Events according to OpenTelemetry standards',
      'Configure head-based and tail-based trace sampling to control storage costs',
    ],
    keyTradeoffs: [
      '100% trace sampling cost vs probabilistic sampling missing critical rare errors',
      'Automatic framework instrumentation vs manual domain-specific span instrumentation',
    ],
    commonPitfalls: [
      'Breaking context propagation in asynchronous background promises or thread pools',
      'Adding high-cardinality PII (like customer email addresses) to trace attributes',
    ],
    transferTopicId: 'obs-structured-logging',
    transferPrompt: 'How do you inject trace IDs and span IDs into structured log records for unified log-trace correlation?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 25,
    tags: ['observability', 'opentelemetry', 'tracing', 'monitoring'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'obs-structured-logging',
    title: 'Centralized Structured Logging & Correlation IDs',
    category: 'observability',
    difficulty: 'beginner',
    prerequisites: ['api-restful-design'],
    learningObjectives: [
      'Emit JSON logs with standardized keys: timestamp, level, reqId, err, and service',
      'Propagate correlation IDs through all downstream network calls and async jobs',
      'Redact sensitive credentials, auth headers, and PII automatically in log serializers',
    ],
    keyTradeoffs: [
      'Synchronous console logging vs asynchronous buffered batch log shipping (Pino/Winston)',
      'Verbose debug logging cost vs production diagnostic visibility',
    ],
    commonPitfalls: [
      'Logging raw request bodies containing plaintext passphrases or unmasked credit card numbers',
      'Emitting unstructured multi-line text strings that break automated log parsers',
    ],
    transferTopicId: 'obs-slos-alerting',
    transferPrompt: 'How are structured log metrics aggregated to calculate service error rates and alert on outages?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 15,
    tags: ['observability', 'logging', 'pino', 'security'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'obs-slos-alerting',
    title: 'SLIs, SLOs & Error Budget Alerting',
    category: 'observability',
    difficulty: 'intermediate',
    prerequisites: ['obs-structured-logging'],
    learningObjectives: [
      'Define Service Level Indicators (SLIs) for latency (p95, p99) and availability',
      'Establish meaningful Service Level Objectives (SLOs) and calculate 30-day error budgets',
      'Implement multi-window multi-burn-rate alerting to eliminate page fatigue',
    ],
    keyTradeoffs: [
      'Aggressive alerting sensitivity vs false alarm on-call engineer burnout',
      'Freezing product feature deployments when error budgets are exhausted',
    ],
    commonPitfalls: [
      'Alerting on noisy CPU utilization thresholds rather than direct user-impacting error rates',
      'Measuring mean latency instead of high-percentile latency (p99/p99.9)',
    ],
    transferTopicId: 'rel-circuit-breaker',
    transferPrompt: 'When SLO burn rate spikes due to an external API degradation, how does a circuit breaker protect your error budget?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['observability', 'sre', 'slos', 'alerting'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'rel-circuit-breaker',
    title: 'Circuit Breakers & Graceful Degradation',
    category: 'reliability and failure handling',
    difficulty: 'intermediate',
    prerequisites: ['api-restful-design'],
    learningObjectives: [
      'Implement the three-state Circuit Breaker pattern: CLOSED, OPEN, and HALF_OPEN',
      'Track failure thresholds, timeout frequencies, and cooldown recovery windows',
      'Design graceful fallbacks when dependencies fail (cached responses, default states)',
    ],
    keyTradeoffs: [
      'Failing fast with an immediate fallback error vs waiting on upstream connection timeouts',
      'Shared distributed circuit breaker state vs local per-process circuit breaker state',
    ],
    commonPitfalls: [
      'Setting trip thresholds too sensitive, causing cascading circuit trips during momentary network blips',
      'Treating 4xx client errors as upstream service failures that trip the breaker',
    ],
    transferTopicId: 'rel-retry-exponential-jitter',
    transferPrompt: 'How do client-side retry strategies collaborate with circuit breakers without amplifying upstream outages?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['reliability', 'circuit-breaker', 'resilience', 'architecture'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'rel-disaster-recovery',
    title: 'Multi-Region Failover & Disaster Recovery',
    category: 'reliability and failure handling',
    difficulty: 'advanced',
    prerequisites: ['db-sharding-partitioning'],
    learningObjectives: [
      'Define Recovery Point Objective (RPO) and Recovery Time Objective (RTO)',
      'Design Active-Passive and Active-Active multi-region replication architectures',
      'Implement DNS failover and health probing with automated split-brain prevention',
    ],
    keyTradeoffs: [
      'Active-Active write latency across continents vs Active-Passive failover lag',
      'Multi-region infrastructure hosting costs vs business downtime impact',
    ],
    commonPitfalls: [
      'Split-brain scenarios where both regions accept conflicting writes simultaneously',
      'Never testing disaster recovery failover procedures until a real outage occurs',
    ],
    transferTopicId: 'scale-load-balancing',
    transferPrompt: 'How does global anycast routing direct traffic away from an unhealthy data center?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 25,
    tags: ['reliability', 'disaster-recovery', 'failover', 'multiregion'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'rel-retry-exponential-jitter',
    title: 'Retries with Exponential Backoff & Jitter',
    category: 'reliability and failure handling',
    difficulty: 'beginner',
    prerequisites: ['api-restful-design'],
    learningObjectives: [
      'Calculate exponential backoff delays with full jitter: `delay = random(0, min(cap, base * 2^attempt))`',
      'Differentiate retryable transient errors (503, 429, ECONNRESET) from non-retryable errors (400, 401, 404)',
      'Enforce maximum retry attempt limits and overall request deadline timeouts',
    ],
    keyTradeoffs: [
      'Full jitter vs decorrelated jitter in reducing synchronized client thundering herds',
      'Retrying inside application services vs delegating to service mesh sidecars (Envoy)',
    ],
    commonPitfalls: [
      'Retrying non-idempotent write operations, causing duplicate payments or orders',
      'Retrying without random jitter, creating periodic harmonic spikes on recovering servers',
    ],
    transferTopicId: 'rel-circuit-breaker',
    transferPrompt: 'How do retries coordinate with circuit breakers so repeated failed attempts do not exhaust thread pools?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 15,
    tags: ['reliability', 'retries', 'backoff', 'jitter'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'scale-load-balancing',
    title: 'Load Balancing Strategies & Health Probing',
    category: 'scalability',
    difficulty: 'intermediate',
    prerequisites: ['api-restful-design'],
    learningObjectives: [
      'Compare Layer 4 (TCP/UDP) vs Layer 7 (HTTP) load balancing algorithms',
      'Evaluate Round Robin, Least Connections, and Consistent Hashing distribution',
      'Configure deep vs shallow `/healthz` and `/readyz` probes without cascading outages',
    ],
    keyTradeoffs: [
      'Layer 7 path-based routing flexibility vs Layer 4 maximum packet throughput',
      'Sticky sessions (session affinity) vs stateless uniform request distribution',
    ],
    commonPitfalls: [
      'Health check endpoints that query the database, causing all pods to be marked dead when the database is slow',
      'Uneven load distribution caused by long-lived persistent HTTP/2 connections on standard round-robin',
    ],
    transferTopicId: 'scale-cdn-edge-caching',
    transferPrompt: 'How does CDN edge caching reduce load on central application load balancers?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['scalability', 'loadbalancing', 'devops', 'networking'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'scale-cdn-edge-caching',
    title: 'Global CDN Edge Caching & Dynamic Acceleration',
    category: 'scalability',
    difficulty: 'intermediate',
    prerequisites: ['scale-load-balancing'],
    learningObjectives: [
      'Configure `Cache-Control`, `s-maxage`, `stale-while-revalidate`, and ETag headers',
      'Accelerate dynamic API endpoints using TCP connection reuse and edge TLS termination',
      'Design targeted cache purging via surrogate keys (Cache-Tags)',
    ],
    keyTradeoffs: [
      'Aggressive edge caching of semi-dynamic content vs real-time data freshness',
      'Purging cache by exact URL vs wildcard/tag-based invalidation',
    ],
    commonPitfalls: [
      'Accidentally caching authenticated responses with `Set-Cookie` headers at the public CDN edge',
      'Missing `Vary: Accept-Encoding` or `Vary: Origin`, causing CORS or compression corruption',
    ],
    transferTopicId: 'sec-cors-csrf-mitigation',
    transferPrompt: 'How do CDN edge rules enforce Content Security Policies and WAF security rules?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['scalability', 'cdn', 'caching', 'performance'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'sec-cors-csrf-mitigation',
    title: 'Web Security: Strict CORS, CSRF & Content Security Policy',
    category: 'security',
    difficulty: 'intermediate',
    prerequisites: ['auth-email-password'],
    learningObjectives: [
      'Configure strict Cross-Origin Resource Sharing (CORS) allow-lists with origin validation',
      'Prevent Cross-Site Request Forgery (CSRF) using `SameSite=Strict` cookies and double-submit tokens',
      'Deploy strict Content Security Policy (CSP) headers without breaking modern frontend apps',
    ],
    keyTradeoffs: [
      'Using `SameSite=Strict` cookies vs `SameSite=Lax` for external inbound link navigation',
      'CSP `unsafe-inline` convenience vs nonce-based strict script execution',
    ],
    commonPitfalls: [
      'Reflecting the client request `Origin` header dynamically in `Access-Control-Allow-Origin: *` with credentials',
      'Relying solely on CORS to protect against CSRF attacks',
    ],
    transferTopicId: 'sec-sql-xss-prevention',
    transferPrompt: 'How does CSP mitigate the blast radius if an XSS vulnerability occurs in your frontend?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['security', 'cors', 'csrf', 'csp'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'sec-sql-xss-prevention',
    title: 'Injection Prevention & Defense-in-Depth Sanitization',
    category: 'security',
    difficulty: 'beginner',
    prerequisites: ['api-restful-design', 'db-relational-schema'],
    learningObjectives: [
      'Eliminate SQL Injection using parameterized prepared statements via ORMs and query builders',
      'Prevent Stored and Reflected XSS through contextual HTML/attribute escaping',
      'Sanitize dangerous user inputs (e.g. SVG file uploads, markdown HTML tags)',
    ],
    keyTradeoffs: [
      'Raw SQL query control vs parameterized query builder type safety',
      'Stripping HTML tags completely vs allowing an audited whitelist of rich-text tags',
    ],
    commonPitfalls: [
      'Concatenating dynamic user input into SQL queries or table/column identifier strings',
      'Using `dangerouslySetInnerHTML` in React without running DOMPurify sanitization',
    ],
    transferTopicId: 'sec-cors-csrf-mitigation',
    transferPrompt: 'How do defense-in-depth measures like CSP protect users when input sanitization fails?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 15,
    tags: ['security', 'sqli', 'xss', 'sanitization'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'deploy-canary-blue-green',
    title: 'Blue-Green & Canary Deployment Pipelines',
    category: 'deployment',
    difficulty: 'intermediate',
    prerequisites: ['scale-load-balancing'],
    learningObjectives: [
      'Compare Blue-Green instant switch deployments with gradual Canary percentage rollouts',
      'Automate automated rollback triggers on error rate or latency metric anomalies',
      'Maintain backward-compatible database schemas across concurrent running versions',
    ],
    keyTradeoffs: [
      'Double infrastructure footprint cost during Blue-Green deployments vs Canary gradual risk exposure',
      'Sticky canary sessions by user ID vs random percentage request routing',
    ],
    commonPitfalls: [
      'Deploying breaking database schema changes during a blue-green swap, crashing the live version',
      'Failing to monitor canary metrics for subtle errors before rolling out to 100% of production',
    ],
    transferTopicId: 'obs-slos-alerting',
    transferPrompt: 'How do automated canary deployment controllers evaluate SLO burn rates to trigger rollbacks?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 20,
    tags: ['deployment', 'canary', 'blue-green', 'devops'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
  {
    id: 'ai-chat-memory',
    title: 'Conversational AI Context Window Management & Memory',
    category: 'AI/LLM features',
    difficulty: 'advanced',
    prerequisites: ['ai-rag'],
    learningObjectives: [
      'Design context window management: rolling window, semantic summary, and vector retrieval',
      'Extract structured entities and long-term user preferences from conversational history',
      'Manage token budgets across system prompt, retrieved context, chat history, and generation reserve',
    ],
    keyTradeoffs: [
      'Summarization LLM latency and token cost vs loss of verbatim historical dialogue details',
      'Client-side state tracking vs server-managed persistent conversational memory',
    ],
    commonPitfalls: [
      'Exceeding LLM context window limits without a graceful compression or truncation policy',
      'Injecting unsanitized user chat history into system prompt instructions (indirect prompt injection)',
    ],
    transferTopicId: 'ai-rag',
    transferPrompt: 'How do you combine conversational memory with external vector RAG to answer queries grounded in user history?',
    standardSteps: [1, 5, 8, 9],
    estimatedMinutes: 25,
    tags: ['ai', 'llm', 'memory', 'context-window'],
    isCustom: false,
    isActive: true,
    referenceStatus: 'unauthored',
    steps: {},
  },
];

export function generateAllUnauthoredTopics(outputDir: string) {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  let count = 0;
  for (const topicData of UNAUTHORED_TOPICS) {
    const validated = TopicSchema.parse(topicData);
    const filePath = path.join(outputDir, `${validated.id}.json`);
    fs.writeFileSync(filePath, JSON.stringify(validated, null, 2), 'utf8');
    count++;
  }

  console.log(`[Topics] Successfully generated and verified ${count} unauthored topic JSON files.`);
}

const targetDir = path.resolve(process.cwd(), 'packages/learning/topics');
generateAllUnauthoredTopics(targetDir);
